// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "ApiKey",
    columns: [
      { name: "ApiKey", type: "string" },
      { name: "userId", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type ApiKey = InferredTypes["ApiKey"];
export type ApiKeyRecord = ApiKey & XataRecord;

export type DatabaseSchema = {
  ApiKey: ApiKeyRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://satish-s-workspace-6midd6.us-east-1.xata.sh/db/jetdrive",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = (apiKey:string) => {
  if (instance) return instance;

  instance = new XataClient(apiKey ? { apiKey } : undefined);
  return instance;
};
